apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coral-app
  template:
    metadata:
      labels:
        app: coral-app
    spec:
      containers:
      - name: app-container
        image: thicoral/coral-app:v1
        imagePullPolicy: Always # <--- ADICIONE ESTA LINHA AQUI
        ports:
        - containerPort: 8000
        env:
        - name: NAI_ENDPOINT
          value: "https://10-54-94-16.sslip.nutanixdemo.com/enterpriseai/v1/chat/completions"
        - name: NAI_API_KEY
          value: "c5e46281-8985-48ae-b367-fe61c7875d71"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: coral-app