apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral-app
  template:
    metadata:
      labels:
        app: coral-app
    spec:
      containers:
      - name: app-container
        image: docker.io/thicoral/coral-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer # Mude de ClusterIP para LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: coral-app