apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-frontend
  namespace: coral-project-krq9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral-frontend
  template:
    metadata:
      labels:
        app: coral-frontend
    spec:
      containers:
      - name: frontend-container
        image: index.docker.io/thicoral/coral-app:frontend # Tag que o GitHub Actions vai gerar
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: coral-project-krq9s
spec:
  type: LoadBalancer
  ports:
  - port: 80         # Porta que você vai digitar no navegador
    targetPort: 8501 # Porta onde o Streamlit está ouvindo
  selector:
    app: coral-frontend