apiVersion: apps/v1
kind: Deployment
metadata:
  name: coral-frontend
  namespace: coral-project-krq9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coral-frontend
  template:
    metadata:
      labels:
        app: coral-frontend
    spec: 
      containers:
      - name: frontend
        image: docker.io/thicoral/coral-app:frontend # Tag correta do GitHub Actions
        imagePullPolicy: Always
        env:
        - name: NAI_ENDPOINT
          value: "https://10-54-94-16.sslip.nutanixdemo.com/enterpriseai/v1/chat/completions"
        - name: NAI_API_KEY
          value: "bac373c4-2607-4c8d-9521-62dd3ed781e9"
        - name: MODEL_NAME
          value: "coral-endpoint"
        ports:
        - containerPort: 8501 # Streamlit padrão
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: coral-project-krq9s
spec:
  type: LoadBalancer
  ports:
  - port: 80         
    targetPort: 8501 
  selector:
    app: coral-frontend