name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Atualizado para v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Atualizado para v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build do BACKEND
      - name: Build and Push Backend
        uses: docker/build-push-action@v5 # Atualizado para v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: thicoral/coral-app:v1

      # Build do FRONTEND
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5 # Atualizado para v5
        with:
          context: .
          file: ./Dockerfile.frontend # O GitHub vai procurar este arquivo agora!
          platforms: linux/amd64
          push: true
          tags: thicoral/coral-app:frontend